### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by q121q** [etzinis/sudo_rm_rf#6]
Hi, 

Thanks for publishing your code, have a few questions I hope are of interest to the greater community:
a) Do you have results for libriMix? Looks like there's code support for that, IIRC the paper doesn't mention any results on it.
b) How long should it take to train? Would a single 2080 be enough to train on libriMix in one day?
c) Can you provide any pretrained checkpoints?

Thanks

**Comment by etzinis** [comment]
Thanks for reaching out.
a) I had some initial experiments but did not test fully since I just did this experiment to see what am I getting. THe results were similar to other architectures.
b) It depends on the level of convergence and your model. You should be able to get reasonable numbers after 1 day of training.
c) Working towards that, thanks for bringing that up!

**Comment by etzinis** [comment]
Please check my latest commit containign anechoic and noisy/reverberant mixture checkpoints.

**Comment by JusperLee** [comment]
> Please check my latest commit containign anechoic and noisy/reverberant mixture checkpoints.

Our paper lists the main results of LibriMix. [AFRCNN](https://papers.nips.cc/paper/2021/file/be1bc7997695495f756312886f566110-Paper.pdf)
